import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(6,7.5))
Nmax = 200
Amax = 12

ax = plt.subplot(321)
plt.ylabel(r'$|A|*10^{-4}$')
plt.grid()
plt.xlim(0, Nmax)
plt.ylim(0, Amax)
plt.setp(ax.get_xticklabels(), visible=False)
ax.ticklabel_format(useOffset=False)
#ax.ticklabel_format(useMathText=True)
data = np.loadtxt('fractal14_AverFFT.txt')
plt.plot(data[:Nmax]/10000)

ax = plt.subplot(322)
plt.grid()
plt.xlim(0, Nmax)
plt.ylim(0, Amax)
plt.setp(ax.get_xticklabels(), visible=False)
plt.setp(ax.get_yticklabels(), visible=False)
data = np.loadtxt('fractal15_AverFFT.txt')
plt.plot(data[:Nmax]/10000)

ax = plt.subplot(323)
plt.ylabel(r'$|A|*10^{-4}$')
plt.grid()
plt.xlim(0, Nmax)
plt.ylim(0, Amax)
plt.setp(ax.get_xticklabels(), visible=False)
data = np.loadtxt('fractal16_AverFFT.txt')
plt.plot(data[:Nmax]/10000)

ax = plt.subplot(324)
plt.grid()
plt.xlim(0, Nmax)
plt.ylim(0, Amax)
plt.setp(ax.get_xticklabels(), visible=False)
plt.setp(ax.get_yticklabels(), visible=False)
data = np.loadtxt('fractal17_AverFFT.txt')
plt.plot(data[:Nmax]/10000)

ax = plt.subplot(325)
plt.ylabel(r'$|A|*10^{-4}$')
plt.xlabel(r'$n - 1$')
plt.grid()
plt.xlim(0, Nmax)
plt.ylim(0, Amax)
data = np.loadtxt('fractal18_AverFFT.txt')
plt.plot(data[:Nmax]/10000)

ax = plt.subplot(326)
plt.xlabel(r'$n - 1$')
plt.grid()
plt.xlim(0, Nmax)
plt.ylim(0, Amax)
plt.setp(ax.get_yticklabels(), visible=False)
ax.ticklabel_format(useOffset=False)
data = np.loadtxt('fractal19_AverFFT.txt')
plt.plot(data[:Nmax]/10000)

plt.savefig('fft-spectras-new.png', dpi=600)
plt.show()