import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(6,7.5))
Nmax = 200
Amax = 12

ax = plt.subplot(321)
ax.set_aspect(1)
plt.ylabel(r'$y$')
plt.setp(ax.get_xticklabels(), visible=False)
plt.setp(ax.get_yticklabels(), visible=False)
ax.tick_params(axis='both', which='both', length=0)
data = np.loadtxt('./fractal1/contour600.txt')
plt.plot(data[:,0],data[:,1])

ax = plt.subplot(322)
ax.set_aspect(1)
#plt.xlim(0, Nmax)
#plt.ylim(0, Amax)
plt.setp(ax.get_xticklabels(), visible=False)
plt.setp(ax.get_yticklabels(), visible=False)
ax.tick_params(axis='both', which='both', length=0)
data = np.loadtxt('./fractal2/contour600.txt')
plt.plot(data[:,0],data[:,1])

ax = plt.subplot(323)
ax.set_aspect(1)
plt.ylabel(r'$y$')
#plt.xlim(0, Nmax)
#plt.ylim(0, Amax)
plt.setp(ax.get_xticklabels(), visible=False)
plt.setp(ax.get_yticklabels(), visible=False)
ax.tick_params(axis='both', which='both', length=0)
data = np.loadtxt('./fractal3/contour600.txt')
plt.plot(data[:,0],data[:,1])

ax = plt.subplot(324)
ax.set_aspect(1)
plt.setp(ax.get_xticklabels(), visible=False)
plt.setp(ax.get_yticklabels(), visible=False)
ax.tick_params(axis='both', which='both', length=0)
data = np.loadtxt('./fractal4/contour600.txt')
plt.plot(data[:,0],data[:,1])

ax = plt.subplot(325)
ax.set_aspect(1)
plt.ylabel(r'$y$')
plt.xlabel(r'$x$')
plt.setp(ax.get_xticklabels(), visible=False)
plt.setp(ax.get_yticklabels(), visible=False)
ax.tick_params(axis='both', which='both', length=0)
data = np.loadtxt('./fractal5/contour600.txt')
plt.plot(data[:,0],data[:,1])

ax = plt.subplot(326)
ax.set_aspect(1)
plt.xlabel(r'$x$')
plt.setp(ax.get_xticklabels(), visible=False)
plt.setp(ax.get_yticklabels(), visible=False)
ax.ticklabel_format(useOffset=False)
ax.tick_params(axis='both', which='both', length=0)
data = np.loadtxt('./fractal6/contour600.txt')
plt.plot(data[:,0],data[:,1])

plt.savefig('contours-plot-old.png', dpi=600)
plt.show()